name: Update 'latest' tag on push to main

on:
  push:
    branches:
      - main

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or move 'latest' tag to current commit
        run: |
          git tag -f latest
          git push origin latest --force
