name: Update 'latest' tag on push to main

on:
  push:
    branches:
      - main

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update latest tag
        run: |
          git tag -f latest
          git push origin latest --force
